# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        virtual microphone: 5
        virtual signal: 5
        speech separation: 2
        beamforming: 2
        

# 通知の閾値
score_threshold: 0
